image: docker:latest

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.infomania.ru/developers/backend.git".

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker ps
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  needs: [build-job]
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
