stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  image: docker
  stage: build
  script:
    - docker ps
    # - docker build -t vladdamage/infomania_backend .
    # - docker push vladdamage/infomania_backend:latest

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."