version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'diehard'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'example'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - network

#  web:
#    build: .
#    image: vladdamage/infomania_backend
#    container_name: web
#    restart: always
#    ports:
#      - '3333:3001'
#    env_file:
#      - .production.env
#    depends_on:
#      - db
#    networks:
#      - network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - network

  minio:
    image: bitnami/minio:latest
    restart: always
    ports:
      - '10000:9000'
      - '10001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Linerace2010
    networks:
      - network

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6379:6379'
#    volumes:
#      - redis-data:/data
#      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - network

# Names our volume
volumes:
  my-db:

networks:
  network:
    driver: bridge
