version: '3.8'

services:
  web:
    build: .
    image: nixel666/infomania_backend:v2
    container_name: web
    restart: always
    ports:
      - '3333:3000'
    env_file:
      - .production.env


