version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'diehard'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'example'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  web:
    build: .
    image: vladdamage/infomania_backend
    container_name: web
    restart: always
    ports:
      - '3333:3000'
    environment:
      DATABASE_URL: 'mysql://root:example@host.docker.internal:3306/db'
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

  minio:
    image: bitnami/minio:latest
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Linerace2010

# Names our volume
volumes:
  my-db:
