name: Build and Deploy

on: [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Files
        run: ls -la
      - name: Build image
        run: docker-compose -f docker-compose.prod.yml build web
      - name: Push image to docker.io
        run: docker-compose -f docker-compose.prod.yml push web

  deploy:
    runs-on: [ubuntu-latest]
    needs: build_and_publish
    env:
      SSH_CONNECT: ssh -p ${{ secrets.DEPLOY_MACHINE_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_MACHINE_IP }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p 22024 ${{ secrets.DEPLOY_MACHINE_IP }} >> ~/.ssh/known_hosts

      - name: docker pull
        run: $SSH_CONNECT docker-compose pull

      - name: docker up
        run: $SSH_CONNECT docker-compose up -d

      - name: docker clear images
        run: $SSH_CONNECT docker image prune
